commonLabels:
  run: repo
namePrefix: repo-
bases:
- github.com/kmassada/kustomize-starter//base
patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Deployment
    name: app
  path: deployment.patch.yaml
- target:
    version: v1
    kind: Service
    name: app
  path: service.patch.yaml
vars:
  - name: MY_APP_NAME
    objref:
      kind: Deployment
      name: app
      apiVersion: extensions/v1beta1
    fieldref:
      fieldpath: metadata.name